name: LeetTP
main: Leet\LeetTP\LeetTP
version: 1.2.0
api: [2.0.0]
author: ProjectInfinity

commands:
  sethome:
    description: "Sets a home"
    usage: "/sethome <name>"
    permission: "leettp.command.sethome"
  delhome:
    description: "Deletes a home"
    usage: "/delhome <name>"
    permission: "leettp.command.delhome"
  home:
    description: "Teleports home"
    usage: "/home <name>"
    permission: "leettp.command.home"
  homes:
    description: "Lists owned homes"
    usage: "/homes"
    aliases: [listhome]
    permission: "leettp.command.homes"
  warp:
    description: "Warps to target location"
    usage: "/warp <name>"
    permission: "leettp.command.warp"
  setwarp:
    description: "Sets a warp"
    usage: "/setwarp <name> <-p>"
    permission: "leettp.command.setwarp"
  delwarp:
    description: "Deletes a warp"
    usage: "/delwarp <name>"
    permission: "leettp.command.delwarp"
  warps:
    description: "Lists all warps you can access"
    usage: "/warps"
    aliases: [listwarp]
    permission: "leettp.command.warps"
  tpa:
    description: "Asks to teleport to user"
    usage: "/tpa <player>"
    permission: "leettp.command.tpa"
  tpworld:
    description: "Teleports to a world"
    usage: "/tpworld <world>"
    permission: "leettp.command.tpworld"
  tpahere:
    description: "Asks to teleport a player to yourself"
    usage: "/tpahere <player>"
    permission: "leettp.command.tpahere"
  tpaccept:
    description: "Accepts a teleportation request"
    usage: "/tpaccept <player>"
    permission: "leettp.command.tpaccept"
  tpdeny:
    description: "Denies a teleportation request"
    usage: "/tpdeny <player>"
    permission: "leettp.command.tpdeny"
  tpo:
    description: "Teleports player to another player that is denying tp requests"
    usage: "/tpo <player>"
    permission: "leettp.command.tpo"
  tpohere:
    description: "Teleports player to yourself when target is denying tp requests"
    usage: "/tpohere <player>"
    permission: "leettp.command.tpohere"
  tptoggle:
    description: "Toggle whether you allow teleportation requests or not"
    usage: "/tptoggle"
    permission: "leettp.command.tptoggle"
  back:
    description: "Teleports you to your last recorded death location"
    usage: "/back"
    permission: "leettp.command.back"
  spawn:
    description: "Teleports the sender to spawn"
    usage: "/spawn"
    permission: "leettp.command.spawn"
  setspawn:
    description: "Sets the spawn for the current world."
    usage: "/setspawn"
    permission: "leettp.command.setspawn"

permissions:
  leettp.command.sethome:
    default: true
    description: "Allow creation of homes"
  leettp.command.home:
    default: true
    description: "Allow teleporting to homes"
  leettp.command.homes:
    default: true
    description: "Allow listing of owned homes"
  leettp.command.delhome:
    default: true
    description: "Allow deletion of homes"
  leettp.command.warp:
    default: true
    description: "Allow teleportation to warps"
  leettp.command.setwarp:
    default: op
    description: "Allow creation of warps"
  leettp.command.delwarp:
    default: op
    description: "Allow deletion of warps"
  leettp.command.warps:
    default: true
    description: "Allow listing of warps"
  leettp.command.tpa:
    default: true
    description: "Allow asking to teleport to player"
  leettp.command.tpahere:
    default: true
    description: "Allow asking to teleport player to yourself"
  leettp.command.tpaccept:
    default: true
    description: "Allow accepting teleportation requests"
  leettp.command.tpdeny:
    default: true
    description: "Allow denying teleportation requests"
  leettp.command.tptoggle:
    default: true
    description: "Allow user to toggle whether to allow tp requests or not"
  leettp.command.tpworld:
    default: true
    description: "Allow teleportation to a different world."
  leettp.command.tpo:
    default: op
    description: "Allow teleporting to players that don't allow teleport requests"
  leettp.command.tpohere:
    default: op
    description: "Allow teleporting a player to do you that don't allow teleport requests"
  leettp.command.back:
    default: true
    description: "Allow teleporting back to last recorded death location"
  leettp.command.spawn:
    default: true
    description: "Allow teleporting to spawn"
  leettp.command.setspawn:
    default: op
    description: "Allow setting the spawn location of the current world"
  leettp.warp.public:
    default: op
    description: "Allow to make warps as public"